[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20', 'npm']

[phases.install]
dependsOn = ['setup']
cmds = [
    'composer install --optimize-autoloader --no-dev --no-interaction',
    'npm install && npm run build',
    'chmod -R 775 storage bootstrap/cache'
]

[phases.build]
dependsOn = ['install']
cmds = ['php artisan optimize:clear']

[start]
# Gunakan migrate:fresh hanya UNTUK SEKARANG agar tabel dibuat ulang dari nol
cmd = "php artisan migrate:fresh --force && php artisan db:seed --force && php artisan serve --host 0.0.0.0 --port $PORT"