[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20', 'npm']

[phases.install]
dependsOn = ['setup']
cmds = [
    'composer install --optimize-autoloader --no-dev --no-interaction',
    'npm install && npm run build',
    'chmod -R 775 storage bootstrap/cache'
]

[phases.build]
dependsOn = ['install']
cmds = ['php artisan optimize:clear']

[start]
cmd = "php artisan migrate --force && php artisan optimize && php-fpm -D && nginx -g 'daemon off;'"